# Generated by Django 6.0.4 on 2026-05-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='CNIC',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='cnic_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='cnic_images/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cnic_verified',
            field=models.BooleanField(default=False),
        ),
    ]
